'use strict';
const {summary:S,detail:D}=window.DPM_DATA;
const $=id=>document.getElementById(id),fmt=n=>Number(n).toLocaleString('ko-KR',{maximumFractionDigits:3,minimumFractionDigits:3});
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const heroes=[...new Set(S.map(r=>r.hero))].sort((a,b)=>a.localeCompare(b,'ko'));
const dense=r=>r.target.startsWith('밀집'),variant=r=>r.rune.replace('·밀집 보스 2명 합산','').replace(/^없음·?/,'')||'기본';
const state={hero:heroes[0],boss:'single',level:null,variant:null,rankLevel:'max',sort:'desc'};
const image=h=>esc(window.DPM_IMAGES[h]),activeRows=()=>S.filter(r=>dense(r)===(state.boss==='dense'));
for(const lv of [...new Set(S.map(r=>r.level))].sort((a,b)=>a-b))$('rank-level').add(new Option(`${lv}레벨`,lv));
function cards(){const names=heroes.filter(h=>h.includes($('search').value.trim()));$('cards').innerHTML=names.length?names.map(h=>`<button class="card" data-hero="${esc(h)}" aria-pressed="${h===state.hero}"><img src="${image(h)}" alt="" loading="lazy"><span>${esc(h)}</span></button>`).join(''):'<p class="empty">검색 결과가 없습니다.</p>';}
function ranking(){let rows=activeRows().filter(r=>state.rankLevel==='all'||r.level===(state.rankLevel==='max'?Math.max(...S.filter(x=>x.hero===r.hero).map(x=>x.level)):Number(state.rankLevel)));rows.sort((a,b)=>(state.sort==='name'?a.hero.localeCompare(b.hero,'ko'):state.sort==='asc'?a.dpmB-b.dpmB:b.dpmB-a.dpmB)||a.hero.localeCompare(b.hero,'ko')||b.level-a.level||variant(a).localeCompare(variant(b),'ko'));const max=Math.max(1,...rows.map(r=>r.dpmB));$('count').textContent=`${rows.length}개 결과`;$('ranks').innerHTML=rows.map((r,i)=>`<tr class="${r.hero===state.hero?'selected-row':''}"><td>${i+1}</td><td><button class="rank-link" data-hero="${esc(r.hero)}" data-level="${r.level}" data-variant="${esc(variant(r))}"><img src="${image(r.hero)}" alt="" loading="lazy">${esc(r.hero)}</button></td><td>Lv.${r.level}<span class="variant-text">${esc(variant(r))}</span></td><td><div class="bar"><i style="width:${r.dpmB/max*100}%"></i></div></td><td class="number"><strong>${fmt(r.dpmB)}</strong></td></tr>`).join('');}
function detail(){const rows=activeRows().filter(r=>r.hero===state.hero),levels=[...new Set(rows.map(r=>r.level))].sort((a,b)=>a-b);if(!levels.includes(state.level))state.level=levels.at(-1);const options=rows.filter(r=>r.level===state.level);if(!options.some(r=>variant(r)===state.variant))state.variant=variant(options[0]);const r=options.find(r=>variant(r)===state.variant);$('level').innerHTML=levels.map(l=>`<option value="${l}" ${l===state.level?'selected':''}>${l}레벨</option>`).join('');$('variant').innerHTML=options.map(x=>`<option ${variant(x)===state.variant?'selected':''}>${esc(variant(x))}</option>`).join('');$('hero-name').textContent=state.hero;$('hero-image').src=window.DPM_IMAGES[state.hero];$('context').textContent=`Lv.${r.level} · ${state.variant} · ${state.boss==='single'?'보스 1명':'밀집 보스 2명 합산'}`;
$('metrics').innerHTML=[['분당 피해량',fmt(r.dpmB),'B DPM'],['300초 총피해',fmt(r.totalB),'B'],['최종 공격력',fmt(r.attackK),'K'],['공격속도',fmt(r.attackSpeed),'회/초']].map(([n,v,u])=>`<div class="metric"><span>${n}</span><b>${v}</b> <small>${u}</small></div>`).join('');
const sources=D.filter(x=>x.hero===r.hero&&x.level===r.level&&x.rune===r.rune).sort((a,b)=>b.totalB-a.totalB);$('sources').innerHTML=sources.map(x=>`<div class="source"><div class="source-line"><span>${esc(x.source)}</span><strong>${fmt(x.totalB/5)} B</strong></div><small>기대 ${Number(x.count).toLocaleString('ko-KR',{maximumFractionDigits:2})}회 · 피해 비중 ${(x.totalB/(r.totalB||1)*100).toFixed(1)}%</small><div class="bar"><i style="width:${x.totalB/(r.totalB||1)*100}%"></i></div></div>`).join('');
const growth=rows.filter(x=>variant(x)===state.variant).sort((a,b)=>a.level-b.level),max=Math.max(1,...growth.map(x=>x.dpmB));$('growth').innerHTML=growth.map(x=>`<div class="level-row"><span>Lv.${x.level}</span><div class="bar"><i style="width:${x.dpmB/max*100}%"></i></div><b>${fmt(x.dpmB)}</b></div>`).join('');$('note').textContent=window.DPM_AUDIT.find(x=>x.hero===state.hero)?.note||r.note;window.renderRunes(S.indexOf(r));}
function selectHero(hero,level=null,v=null){state.hero=hero;state.level=level;state.variant=v;cards();ranking();detail();$('detail').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});$('detail').focus({preventScroll:true});}
$('cards').addEventListener('click',e=>{const b=e.target.closest('[data-hero]');if(b)selectHero(b.dataset.hero);});$('ranks').addEventListener('click',e=>{const b=e.target.closest('[data-hero]');if(b)selectHero(b.dataset.hero,Number(b.dataset.level),b.dataset.variant);});$('search').oninput=cards;
$('rank-level').onchange=e=>{state.rankLevel=e.target.value;ranking();};$('sort').onchange=e=>{state.sort=e.target.value;ranking();};$('level').onchange=e=>{state.level=Number(e.target.value);detail();};$('variant').onchange=e=>{state.variant=e.target.value;detail();};
document.querySelectorAll('[data-boss]').forEach(b=>b.onclick=()=>{state.boss=b.dataset.boss;document.querySelectorAll('[data-boss]').forEach(x=>x.setAttribute('aria-pressed',x===b));ranking();detail();});cards();ranking();detail();
